# Generated by Django 4.0.6 on 2022-08-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
