# Generated by Django 4.0.6 on 2022-08-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos'),
        ),
    ]
