# Generated by Django 4.0.6 on 2022-08-06 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='modalidad',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
