# Generated by Django 4.0.6 on 2022-08-10 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0003_evento_created_evento_fecha_evento_hora_evento_lugar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
