# Generated by Django 4.0.6 on 2022-08-11 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0004_evento_creador_evento_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(related_name='inscriptos', to=settings.AUTH_USER_MODEL),
        ),
    ]
