# Generated by Django 4.0.6 on 2022-08-12 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0005_alter_evento_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(blank=True, default=None, related_name='inscriptos', to=settings.AUTH_USER_MODEL),
        ),
    ]
