# Generated by Django 4.0.6 on 2022-08-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_evento_imagen_alter_evento_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_eventos'),
        ),
    ]
